### ISSUE TITLE
Attribute values in the variant selector are stored wrong in the Database

### ISSUE THREAD

**Issue by martin-netprofit** [leadingsystems/contao-merconis#61]
After an update, the Module/Shop saves the attribute values of variants incorrectly in the database. 
The quotation marks are replaced by  `&#34;`

As a result, the fields can no longer be read out in the templates.

In the Database:
![Bildschirmfoto 2021-09-02 um 12 06 54](https://user-images.githubusercontent.com/25613502/131825708-6aad0085-78ab-4045-a927-723cb7a1fa72.jpg)

Environment:
Contao 4.4.57
Module Merconis: 4.0.8
PHP: 7.2

**Comment by martin-netprofit** [comment]
Is it a bug or is something wrong with my environment? 
Can someone reproduce the problem/bug?

**Comment by vstuber** [comment]
What exactly did you update? Was it just the Contao update to 4.9.20 or did you also update Merconis from an earlier version?

**Comment by martin-netprofit** [comment]
Sorry 😅 the version numbers of Contao and the Modul was wrong in my post (don't ask me why 😅 now they are correct)
I updated Contao and the Merconis-Modul at the same time, but it was just a small version jump by both.

@vstuber Thank you for your help 🙂
 If you need access to the system, let me know.

**Comment by vstuber** [comment]
@martin-netprofit Access to your project would be really helpful. Please contact the Merconis techSupport (https://www.merconis.com/contao-support-webshop-onlineshop-modul.html#contentboxsmall-support) by email to provide the access information.

**Comment by vstuber** [comment]
We found out that the problem is caused by a BC-breaking change in Contao 4.9.18. Beginning with this Contao version JSON code is being html-entity-encoded in some situations. The JSON code is thereby rendered invalid and it is necessary for Merconis to decode it before using it. Because of this BC-Break in Contao we have a whole lot to fix which will definitely take a lot of time.

@martin-netprofit The solution for you is, of course, to downgrade Contao to 4.9.17 and stay at this version until a fix in Merconis becomes available.

**Comment by martin-netprofit** [comment]
ok, thank you for your research 🙂 
Does Contao 4.4.57 have the same problem as Contao 4.9.18?

**Comment by vstuber** [comment]
Yes, Contao 4.4.57 introduced the same BC-breaking change.

**Comment by martin-netprofit** [comment]
Do you already know when the fix will come?

**Comment by martin-netprofit** [comment]
?

**Comment by chiron501** [comment]
Hi, we have fixed the error. 
You can update Merconis to version 4.0.8.5 to fix the bug.
